### PR TITLE
Add vic exposure sites data pull

### PR DESCRIPTION
**Pull request by katiaeirin**

### CODE REVIEW

**Review by phocks — APPROVED** [review]
Looks pretty good to me

**Comment by katiaeirin** [comment]
Awesome thanks!

**Comment by katiaeirin** [comment]
Do you think you will be able to pull and deploy this some time today? 🙏

**Comment by phocks** [comment]
Yep can do

**Comment by phocks** [comment]
Cursor_and_nd_newsdev3____Services_covid19-data-import-function

OK. Should be updated.

**Comment by katiaeirin** [comment]
Amazing thank you so much!

**Pull request merged**
